// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}

declare global {
	namespace NodeJS {
			interface ProcessEnv extends CloudflareEnv {
			}
	}
}//extends process.env to have new types given by cloudflare

export type {};