import type { Metadata } from "next";
import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";
import TranslationsProvider from "@/components/TranslationsProvider";
import { ReactProps } from "@/types/defaultProps";
import initTranslations from "../i18n";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const vazirmatn = Vazirmatn({ subsets: ["arabic"] });

export default async function RootLayout({ children, local = "fa" }: ReactProps) {
  const { resources } = await initTranslations();
  const fontClassName = local === "fa" ? vazirmatn.className : inter.className;
  
  return (
    <html lang={local} dir={local === "fa" ? "rtl" : "ltr"}>
      <TranslationsProvider resources={resources} local={local}>
        <body className={fontClassName}>{children}</body>
      </TranslationsProvider>
    </html>
  );
}
