import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TranslationsProvider from "@/components/TranslationsProvider";
import { ReactProps } from "@/types/defaultProps";
import initTranslations from "../i18n";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({ children, locale }: ReactProps) {
  const { resources } = await initTranslations(locale);

  return (
    <html lang={locale} dir={locale === "fa" ? "rtl" : "ltr"}>
      <TranslationsProvider resources={resources} locale={locale}>
        <body className={inter.className}>{children}</body>
      </TranslationsProvider>
    </html>
  );
}
